#!/bin/tcsh 

# Test case: JW Baroclinic instability 
# default is no rotation, with u perturbation
set u_perturb = 1
set rotate = 0

                  # number of elemnets:  6*ne*ne
set ne = 16        # horizontal resolution   4,16,30,60,120,240
set qsize = 4     # use 4 tracers for testing
set nlev=26       # vertical resolution

set namelist = jw_baroclinic.nl
set mesh_file = /dev/null
set hypervis_scaling = 0
set hypervis_subcycle=3

if ( $ne == 16 ) then
   set tstep=600
   set nu=7e15
endif

# diagnostics printed to stdout
set sfreq = 8   # number of hours
@ sfreq *= 3600
@ sfreq /= $tstep

mkdir -p movies

# default: assume pure sigma levels:
set vfile_mid     = "./camm-26.ascii"
set vfile_int     = "./cami-26.ascii"

#  create a new namelist from original ne16 template:
rm -f input.nl
sed s/ne=.\*/ne=$ne/ jw_baroclinic.nl |\
sed s/tstep=.\*/tstep=$tstep/ | \
sed s/nu=.\*/nu=$nu/ | \
sed s/nu_div=.\*/nu_div=$nu/ | \
sed s/nu_p=.\*/nu_p=$nu/ | \
sed s/nu_q=.\*/nu_q=$nu/ | \
sed s/NThreads.\*/NThreads=1/ | \
sed s/statefreq.\*/statefreq=$sfreq/ |\
sed s/hypervis_scaling.\*/hypervis_scaling=$hypervis_scaling/ |\
sed s/hypervis_subcycle.\*/hypervis_subcycle=$hypervis_subcycle/ |\
sed s/u_perturb.\*/"u_perturb = $u_perturb"/   |\
sed s/rotate_grid.\*/"rotate_grid = $rotate"/  |\
sed s:mesh_file.\*:mesh_file="'$mesh_file'": | \
sed s:vfile_mid.\*:"vfile_mid = '$vfile_mid'":  |\
sed s:vfile_int.\*:"vfile_int = '$vfile_int'":  |\
sed s/qsize.\*/"qsize = $qsize"/  > input.nl

date
./theta < input.nl
date

ncl zeta.ncl
