#!/bin/tcsh 

#SBATCH -A climalg  # Allocation
#SBATCH -p pdebug   # pbatch or pdebug
#SBATCH -N 1        # nodes
#SBATCH -t 00:30:00 # hh:mm:ss
#SBATCH -o temp.out #
#SBATCH -e temp.err #

setenv OMP_NUM_THREADS 1

# Test case: JW Baroclinic instability 
# default is no rotation, with u perturbation
set u_perturb = 1
set rotate = 0
#set tstep_type = 1 # RK2
#set tstep_type = 5 # U35
#set tstep_type = 10 # ARKode RK2
set tstep_type = 11 # ARKode U35

                  # number of elemnets:  6*ne*ne
set ne = 16        # horizontal resolution   4,16,30,60,120,240
set qsize = 4     # use 4 tracers for testing
set nlev=26       # vertical resolution

set namelist = jw_baroclinic.nl
set mesh_file = /dev/null
set hypervis_scaling = 0
set hypervis_subcycle=3

if ( $ne == 16 ) then
   set tstep=1
   set nu=7e15
endif

# diagnostics printed to stdout
set sfreq = 1   # number of hours

mkdir -p movies

# default: assume pure sigma levels:
set vfile_mid     = "./camm-26.ascii"
set vfile_int     = "./cami-26.ascii"

#  create a new namelist from original ne16 template:
rm -f input.nl
sed s/ne=.\*/ne=$ne/ jw_baroclinic.nl |\
sed s/ndays.\*/ndays=0/ | \
sed s/tstep_type.\*/tstep_type=$tstep_type/ | \
sed s/tstep=.\*/tstep=$tstep/ | \
sed s/rsplit=.\*/rsplit=0/ | \
sed s/theta_hydrostatic_mode=.\*/theta_hydrostatic_mode=.true./ | \
sed s/nu=.\*/nu=$nu/ | \
sed s/nu_div=.\*/nu_div=$nu/ | \
sed s/nu_p=.\*/nu_p=$nu/ | \
sed s/nu_q=.\*/nu_q=$nu/ | \
sed s/NThreads.\*/NThreads=$OMP_NUM_THREADS/ | \
sed s/statefreq.\*/statefreq=$sfreq/ |\
sed s/hypervis_scaling.\*/hypervis_scaling=$hypervis_scaling/ |\
sed s/hypervis_subcycle.\*/hypervis_subcycle=$hypervis_subcycle/ |\
sed s/u_perturb.\*/"u_perturb = $u_perturb"/   |\
sed s/rotate_grid.\*/"rotate_grid = $rotate"/  |\
sed s:mesh_file.\*:mesh_file="'$mesh_file'": | \
sed s:vfile_mid.\*:"vfile_mid = '$vfile_mid'":  |\
sed s:vfile_int.\*:"vfile_int = '$vfile_int'":  |\
sed s/output_timeunits=.\*/"output_timeunits=0"/ |\
sed s/output_frequency=.\*/"output_frequency=1"/ |\
sed s/output_varnames1=.\*/"output_varnames1='u','v','T'"/|\
sed s/qsize.\*/"qsize = $qsize"/  > input.nl

date
srun -n 16 -p pdebug ./theta < input.nl
date
